### ISSUE TITLE
please check against new Crypt::OpenSSL::RSA 0.29

### ISSUE THREAD

**Issue by rurban** [kmx/perl-Crypt-OpenSSL-Bignum#1]
no problem, just a reminder to check:
https://github.com/monken/Crypt-OpenSSL-RSA/pull/3

I've tested it against your 4454415 and found no problem.

**Comment by kmx** [comment]
FYI I have just released https://metacpan.org/release/KMX/Crypt-OpenSSL-Bignum-0.05_01 with some non-trivial changes/updates/additions.

It seems to work nice with the latest versions of your https://github.com/rurban/Crypt-OpenSSL-Random + https://github.com/rurban/Crypt-OpenSSL-RSA

**Comment by rurban** [comment]
Thanks! Now you just need to ask modules@perl.org for co-maint. 
Ian Robertson already contacted us (cc to modules@) how to pass the torch over to us, so this is easy.
