### ISSUE TITLE
Please support macOS

### ISSUE THREAD

**Issue by twogee** [kmx/perl-Crypt-OpenSSL-Bignum#3]
Since macOS does not include OpenSSL any more, please add environment variable OPENSSL_PREFIX in Makefile.PL to locate macbrew (currently /usr/local/opt/openssl and /usr/local/opt/openssl@1.1)

**Comment by kmx** [comment]
would it work when we use the output of `pkg-config --libs openssl` and `pkg-config --cflags openssl` ?

**Comment by twogee** [comment]
no, because macOS still provides pkgconfig files and old libraries (0.9.7 and 0.9.8), but no headers (at least on my Sierra upgraded from El Capitan -- sorry for not investigating this properly); homebrew does not provide correct pkgconfig files -- should I report this as an issue to them?

**Comment by kmx** [comment]
I have just uploaded Crypt-OpenSSL-Bignum-0.07 which supports OPENSSL_PREFIX env variable.

Thanks for your bug report.

**Comment by twogee** [comment]
Thanks, could you please do the same for Crypt::OpenSSL::DSA?

**Comment by kmx** [comment]
Done, see Crypt-OpenSSL-DSA-0.16

**Comment by twogee** [comment]
You left `'LIBS'              => ['-lcrypto'],` in Makefile.PL there... and you'll need `'INC'               => $inc,`, too.

**Comment by karel-m** [comment]
you are right, try Crypt-OpenSSL-DSA-0.17

**Comment by kmx** [comment]
you are right, try Crypt-OpenSSL-DSA-0.17
